spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

server:
  port: 53020
  servlet:
    context-path: /uaa


